### ISSUE TITLE
博主，您好

### ISSUE THREAD

**Issue by WinterChenS** [louyanfeng25/ddd-demo#1]
博主您好，我在掘金看了您写的DDD文章并发现了demo，非常精彩，不过我在对比文章中的工程结构和demo的工程结构发现有些地方对不上，比如domain下并没有adapter，还有聚合根在domain中也是没有的，一点点有疑惑，还望您不要介意，特别感谢您能给出这么好的案例让我们学习。

**Comment by louyanfeng25** [comment]
> 博主您好，我在掘金看了您写的DDD文章并发现了demo，非常精彩，不过我在对比文章中的工程结构和demo的工程结构发现有些地方对不上，比如domain下并没有adapter，还有聚合根在domain中也是没有的，一点点有疑惑，还望您不要介意，特别感谢您能给出这么好的案例让我们学习。

感谢你对我的demo与文章输出的认可。关于你提出的结构问题，我在demo的readme开头说明了奥。博客中是是最开始我做迁移的时候定的架构。但是实际应用上发现庞大的业务系统下面，这样的结构依赖层级关系与结构分层不够清晰。因此我与一些落地DDD实践的朋友们共同讨论了这一块的结构，得出了demo的分层。你可以以demo中的结构为准，后续如果对demo结构有更新改进，也会第一时间更新在demo中。
