### ISSUE TITLE
关于UserApplicationService craete和updateUserName疑问

### ISSUE THREAD

**Issue by kaitezhan** [louyanfeng25/ddd-demo#6]
博主，您好，最近看了下代码，有个不是很懂的地方还请麻烦指教下
UserApplicationService 里面有craete和updateUserName，为什么create 会用到UserCreateAbility去做业务处理，而updateUserName不需要用Ability

**Comment by louyanfeng25** [comment]
> 博主，您好，最近看了下代码，有个不是很懂的地方还请麻烦指教下 UserApplicationService 里面有craete和updateUserName，为什么create 会用到UserCreateAbility去做业务处理，而updateUserName不需要用Ability

这里仅仅只是为了演示Ability的使用场景，如果是demo中的createUser场景，完全可以不需要使用到Ability，因为很简单。Ability你可以理解为很小的一个applicationService，为了体现出多个领域协作的原子化能力而存在。形式上类似于applicationService，定位上类似于domainService
